<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Environment.props" />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>ServerSideTweaks.FeatureProbe</AssemblyName>
    <LangVersion>10</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
</Project>
